<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version> <relativePath/>
    </parent>

    <groupId>com.uniclubconnect</groupId>
    <artifactId>UniClubConnect</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging> <name>UniClubConnect :: Parent POM</name>

    <modules>
        <module>infrastructure/config-server</module>
        <module>infrastructure/eureka-server</module>
        <module>infrastructure/api-gateway</module>
        <module>services/auth-service</module>
        <module>services/user-profile-service</module>
        <module>services/club-service</module>
        <module>services/event-service</module>
        <module>services/registration-service</module>
        <module>services/notification-service</module>
        <module>services/post-service</module>
        <module>services/interaction-service</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2023.0.0</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <optional>true</optional>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>