
spring:
  application:
    name: auth-service
  config:
    # Config Server'dan ayarları import et
    import: "configserver:"
  cloud:
    config:
      # Config Server'ın adresi
      uri: http://localhost:8888
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
gamification:
  rabbitmq:
    exchange: gamification.exchange
    routing-key: gamification.event.user.login