
spring:
  application:
    name: auth-service
  config:
    # Config Server'dan ayarlar? import et
    import: "configserver:"
  cloud:
    config:
      # Config Server'?n adresi
      uri: http://localhost:8888
