spring:
  application:
    name: club-service # Eureka'daki ad? (Gateway rotas? i�in �nemli)
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1