spring:
  application:
    # Bu servisin Eureka'daki adı
    name: user-profile-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
