spring:
  application:
    name: gamification-service
  config:
    import: "configserver:"
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
cloud:
  config:
    uri: http://localhost:8888