spring:
  application:
    name: interaction-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
gamification:
  rabbitmq:
    exchange: gamification.exchange
    routing-key: gamification.event.interaction