spring:
  application:
    name: notification-service

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888

  mail:
    host: localhost
    port: 1025
    username: null
    password: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
